name: "CI Process"

on: [push]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run unit testing
        run: |
          cd src/handlers
          for lambda in */; do
            cd "$lambda"
            echo "\nUNIT TEST: $lambda"
            npm install && npm test
            cd ..
          done

  aws_sam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'

      - name: Install AWS SAM
        run: pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: AWS SAM Validation
        run: sam validate
